### PR TITLE
Feature/65 upgrade requirements

### PR DESCRIPTION
**Pull request by roefem**

### CODE REVIEW

**Review by Wim-De-Clercq — APPROVED** [review]

**Comment by Wim-De-Clercq** [comment]
na test fixes ofc *

**Comment by goessebr** [comment]
> De tests vallen hier nog over `KeyError: "term 'sortLabel' not in namespace 'http://www.w3.org/2004/02/skos/core#'"` @koenedaele wat gebeurt hier best?

available terms in namespace SKOS: https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace/_SKOS.py

**Comment by goessebr** [comment]
Since we decided not to upgrade to the lasted versions of rdflib in https://github.com/OnroerendErfgoed/skosprovider_getty/pull/87#discussion_r756755966. We might as well stick with the current version 4.2.2.

**Comment by Wim-De-Clercq** [comment]
Best leave at 5.0.0, otherwise you can't install both skosprovider_heritagedata (rdflib 4.2.2) and  skosprovider_getty(rdflib 5.0.0) without having a conflict.

**Comment by koenedaele** [comment]
> Best leave at 5.0.0, otherwise you can't install both skosprovider_heritagedata (rdflib 4.2.2) and skosprovider_getty(rdflib 5.0.0) or skosprovider_rdf (rdflib 5.0.0) without having a conflict.

**Comment by koenedaele** [comment]
Oops. Wrong button.

**Comment by koenedaele** [comment]
> > De tests vallen hier nog over `KeyError: "term 'sortLabel' not in namespace 'http://www.w3.org/2004/02/skos/core#'"` @koenedaele wat gebeurt hier best?
> 
> available terms in namespace SKOS: https://github.com/RDFLib/rdflib/blob/master/rdflib/namespace/_SKOS.py

Pretty sure I had that error in another place as well. It's basically correct in pointing out that 'sortLabel' does not exist in the SKOS namespace. I vaguely recall that it depended on how you construct a certain object. Currently tests seem to be working, is this because of the downgrade to RDFlib 4.2.2?

**Comment by goessebr** [comment]
> Currently tests seem to be working, is this because of the downgrade to RDFlib 4.2.2?

Yes

**Comment by koenedaele** [comment]
See https://github.com/OnroerendErfgoed/skosprovider_getty/blob/eeee01f38366a259b4f310207adfcfbf11f8e5cf/skosprovider_getty/utils.py where I fixed this before

**Comment by koenedaele** [comment]
sortLabel does not actually exist in the SKOS namespace, it's something we added to do custom sorting. RDFlib considers SKOS to be a closed namespace (can't be extended) so it rightly complains when we claim there is such a thing as SKOS.sortLabel

**Pull request merged**
